#!/usr/bin/env python3
"""
Combinational BCH(31,16,t=3): unfolded BM + 31-way parallel Chien (0-cycle decode).

Micro-architecture triplet:
  bch_ecc_w16_lut.v       — syndrome ROM (5000 lines)
  bch_ecc_w16_fsm.v       — pipelined BM+Chien FSM (~500 lines)
  bch_ecc_w16_pgz_comb.v  — this generator (algebraic comb, ~1500 lines)
"""

from __future__ import annotations

import os
import sys
from typing import List

sys.path.insert(0, os.path.dirname(__file__))
from bch_codec import BCHCodec  # noqa: E402
from emit_comb_bm_verilog import emit_comb_bm  # noqa: E402
from generate_bch_decoder_fsm import (  # noqa: E402
    emit_const_mult_module,
    emit_gf_inv_module,
    emit_gf_mul_module,
)
from generate_bch_repaired_verilog import extract_encoder_block, read_raw_module  # noqa: E402
from generate_bch_verilog import GF2m as GenGF2m, emit_syndrome_wires  # noqa: E402

MOD = "bch_ecc_w16_pgz_comb"
MUL = "gf_mul_w5_comb"
INV = "gf_inv_w5_comb"
_WIDTH, _T, _PP, _N = 16, 3, 0b100101, 31
_M = 5


def emit_w16_wrapper(out_dir: str) -> None:
    body = f"""// BCH(31,16) triplet wrapper: LUT | FSM | PGZ_COMB
module bch_ecc_w16 (
    input  wire clk, input  wire rst_n,
    input  wire encode_en, input  wire decode_en,
    input  wire [15:0] data_in, input  wire [30:0] codeword_in,
    output wire [30:0] codeword_out, output wire [15:0] data_out,
    output wire error_detected, output wire error_corrected, output wire valid_out
);
`ifdef USE_PGZ_COMB
    {MOD} u_core (
`elsif USE_PGZ_FSM
    bch_ecc_w16_fsm u_core (
`else
    bch_ecc_w16_lut u_core (
`endif
        .clk(clk), .rst_n(rst_n), .encode_en(encode_en), .decode_en(decode_en),
        .data_in(data_in), .codeword_in(codeword_in),
        .codeword_out(codeword_out), .data_out(data_out),
        .error_detected(error_detected), .error_corrected(error_corrected),
        .valid_out(valid_out)
    );
endmodule
"""
    with open(os.path.join(out_dir, "bch_ecc_w16.v"), "w", encoding="utf-8") as f:
        f.write(body)
    print(f"Wrote {out_dir}/bch_ecc_w16.v")


def emit_parallel_chien(lam: List[str], gf, t: int, n: int) -> List[str]:
    lines: List[str] = []
    m = gf.m
    for pos in range(n):
        xval = gf.alpha_pow(-pos)
        lines.append(f"    wire [{m - 1}:0] chien_h{t}_{pos};")
        lines.append(f"    assign chien_h{t}_{pos} = {lam[t]};")
        for i in range(t - 1, -1, -1):
            lines.append(f"    wire [{m - 1}:0] chien_p{i}_{pos};")
            lines.append(
                f"    {MUL} u_ch_p{i}_{pos} (.a(chien_h{i + 1}_{pos}), "
                f".b({m}'d{xval}), .y(chien_p{i}_{pos}));"
            )
            lines.append(
                f"    wire [{m - 1}:0] chien_h{i}_{pos} = chien_p{i}_{pos} ^ {lam[i]};"
            )
        lines.append(
            f"    wire ch_root_{pos} = any_syndrome && (chien_h0_{pos} == {m}'d0);"
        )
    lines.append(f"    wire [{n - 1}:0] err_mask;")
    for pos in range(n):
        lines.append(f"    assign err_mask[{pos}] = ch_root_{pos};")
    return lines


def generate(out_dir: str) -> None:
    codec = BCHCodec.for_width(_WIDTH)
    gf = codec.gf
    gen_gf = GenGF2m(_M, _PP)
    raw = read_raw_module(_WIDTH)

    parts = [
        "// Auto-generated by src/generate_bch_w16_pgz_comb.py",
        f"// BCH({_N},{_WIDTH},t={_T}) combinational BM + parallel Chien",
        "",
        emit_gf_mul_module(MUL, gf),
        "",
        emit_gf_inv_module(INV, gf),
        "",
    ]

    v: List[str] = [
        f"module {MOD} (",
        "    input  wire clk, input  wire rst_n,",
        "    input  wire encode_en, input  wire decode_en,",
        f"    input  wire [{_WIDTH - 1}:0] data_in,",
        f"    input  wire [{_N - 1}:0] codeword_in,",
        f"    output reg  [{_N - 1}:0] codeword_out,",
        f"    output reg  [{_WIDTH - 1}:0] data_out,",
        "    output reg  error_detected, output reg  error_corrected, output reg  valid_out",
        ");",
        f"    localparam integer BM_SIZE = {2 * _T + _T + 1};",
    ]
    v.append(extract_encoder_block(raw))
    emit_syndrome_wires(v, gen_gf, _N, _T)

    syn: List[str] = []
    for j in range(1, 2 * _T + 1):
        bits = "{" + ", ".join(f"synd_{j}_{b}" for b in reversed(range(_M))) + "}"
        v.append(f"    wire [{_M - 1}:0] synd_gf_{j} = {bits};")
        syn.append(f"synd_gf_{j}")
    chunks = [f"synd_{j}_{b}" for j in range(1, 2 * _T + 1) for b in range(_M)]
    v.append(f"    wire [{2 * _T * _M - 1}:0] synd_bus = {{ {', '.join(reversed(chunks))} }};")
    v.append("    wire any_syndrome = |synd_bus;")

    # PGZ paper taps (S1^3+S3, S1^2*S3+S5, L2 hint)
    v += [
        f"    wire [{_M - 1}:0] pgz_s1 = synd_gf_1, pgz_s3 = synd_gf_3, pgz_s5 = synd_gf_5;",
        "    wire [4:0] pgz_s1_sq, pgz_s1_cb, pgz_s1_sq2, pgz_s1s3, pgz_inv_delta, pgz_l2_hint;",
        f"    {MUL} u_pgz_s1sq (.a(pgz_s1), .b(pgz_s1), .y(pgz_s1_sq));",
        f"    {MUL} u_pgz_s1cb (.a(pgz_s1_sq), .b(pgz_s1), .y(pgz_s1_cb));",
        f"    wire [{_M - 1}:0] pgz_delta = pgz_s1_cb ^ pgz_s3;",
        f"    {MUL} u_pgz_s1sq2 (.a(pgz_s1_sq), .b(pgz_s1_sq), .y(pgz_s1_sq2));",
        f"    {MUL} u_pgz_s1s3m (.a(pgz_s1_sq2), .b(pgz_s3), .y(pgz_s1s3));",
        f"    wire [{_M - 1}:0] pgz_delta2 = pgz_s1s3 ^ pgz_s5;",
        f"    {INV} u_pgz_invd (.a(pgz_delta), .y(pgz_inv_delta));",
        f"    {MUL} u_pgz_l2 (.a(pgz_delta2), .b(pgz_inv_delta), .y(pgz_l2_hint));",
        "",
    ]

    bm_lines, lam = emit_comb_bm(syn, MUL, INV)
    v.extend(bm_lines)
    lam_w = [f"lambda_{i}" for i in range(_T + 1)]
    for i in range(_T + 1):
        v.append(f"    wire [{_M - 1}:0] {lam_w[i]} = {lam[i]};")
    v.extend(emit_parallel_chien(lam_w, gf, _T, _N))

    pb = codec.parity_bits
    v += [
        f"    wire [{_N - 1}:0] corrected_cw = codeword_in ^ err_mask;",
        "    always @(posedge clk or negedge rst_n) begin",
        "        if (!rst_n) begin",
        f"            codeword_out <= {_N}'b0; data_out <= {_WIDTH}'b0;",
        "            error_detected <= 1'b0; error_corrected <= 1'b0; valid_out <= 1'b0;",
        "        end else if (encode_en) begin",
        f"            codeword_out <= {{data_k, parity}}; data_out <= {_WIDTH}'b0;",
        "            error_detected <= 1'b0; error_corrected <= 1'b0; valid_out <= 1'b1;",
        "        end else if (decode_en) begin",
        f"            codeword_out <= {_N}'b0;",
        f"            data_out <= corrected_cw[{pb + _WIDTH - 1}:{pb}];",
        "            error_detected <= any_syndrome;",
        "            error_corrected <= any_syndrome;",
        "            valid_out <= 1'b1;",
        "        end else valid_out <= 1'b0;",
        "    end",
        "endmodule",
    ]

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"{MOD}.v")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts + v))
    print(f"Wrote {path} ({len(parts) + len(v)} lines)")


def main() -> None:
    root = os.path.join(os.path.dirname(__file__), "..")
    for sub in ("verilogs/repaired_golden/generated", "verilogs/generated"):
        generate(os.path.join(root, sub))
        emit_w16_wrapper(os.path.join(root, sub))


if __name__ == "__main__":
    main()
