#!/usr/bin/env python3
"""
Emit BCH(31,16,t=3) algebraic decoder (BM + parallel Chien FSM).

Multi-cycle FSM twin of bch_ecc_w16_lut.v. Select via bch_ecc_w16.v + `USE_PGZ_FSM.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from generate_bch_decoder_fsm import generate_bch_ecc_fsm  # noqa: E402


def emit_w16_wrapper(out_dir: str) -> None:
    body = """// BCH(31,16) twin wrapper — LUT (default) or PGZ (algebraic FSM)
// Auto-generated by src/generate_bch_w16_pgz.py
module bch_ecc_w16 (
    input  wire clk,
    input  wire rst_n,
    input  wire encode_en,
    input  wire decode_en,
    input  wire [15:0] data_in,
    input  wire [30:0] codeword_in,
    output wire [30:0] codeword_out,
    output wire [15:0] data_out,
    output wire error_detected,
    output wire error_corrected,
    output wire valid_out
);
`ifdef USE_PGZ_COMB
    bch_ecc_w16_pgz_comb u_core (
`elsif USE_PGZ_FSM
    bch_ecc_w16_fsm u_core (
`else
    bch_ecc_w16_lut u_core (
`endif
        .clk(clk),
        .rst_n(rst_n),
        .encode_en(encode_en),
        .decode_en(decode_en),
        .data_in(data_in),
        .codeword_in(codeword_in),
        .codeword_out(codeword_out),
        .data_out(data_out),
        .error_detected(error_detected),
        .error_corrected(error_corrected),
        .valid_out(valid_out)
    );
endmodule
"""
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "bch_ecc_w16.v")
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"Wrote {path}")


def main() -> None:
    root = os.path.join(os.path.dirname(__file__), "..")
    for sub in ("verilogs/repaired_golden/generated", "verilogs/generated"):
        out = os.path.join(root, sub)
        generate_bch_ecc_fsm(out, width=16, module_name="bch_ecc_w16_fsm")
        emit_w16_wrapper(out)


if __name__ == "__main__":
    main()
